### ISSUE TITLE
Comes up without sshd when `run_command: /sbin/init`

### ISSUE THREAD

**Issue by jordansissel** [portertech/kitchen-docker#109]
Data: https://gist.github.com/jordansissel/dc98a4684b2b07b5a3a8

`kitchen converge ...` ends up looping saying:

```
       Waiting for 192.168.59.103:49168...
       Waiting for 192.168.59.103:49168...
       Waiting for 192.168.59.103:49168...
```

Seems like forever, so I checked the docker container:

```
% docker exec $(grep container_id .kitchen/default-ubuntu-1404.yml | fex 2) ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
root         1     0  0 06:25 ?        00:00:00 /sbin/init
root        23     1  0 06:25 ?        00:00:00 @sbin/plymouthd --mode=boot --attach-to-session
root        29     1  0 06:25 ?        00:00:00 plymouth-upstart-bridge
root        32     1  0 06:25 ?        00:00:00 mountall --daemon
root      2893     0  0 06:27 ?        00:00:00 ps -ef
```

Thoughts?

If I `docker exec ...` to start sshd manually, things work ok.

**Comment by jordansissel** [comment]
```
% kitchen version
Test Kitchen version 1.3.1
```

**Comment by jordansissel** [comment]
While `kitchen converge` is waiting, if I do this in another terminal, it recovers quickly:

```
% docker exec 758a5f693186 /etc/init.d/ssh start
 * Starting OpenBSD Secure Shell server sshd
   ...done.
```

**Comment by jordansissel** [comment]
I may be a bit lost also. In an effort to try and reproduce this reliably, I destroyed all containers and images (docker rm + rmi). `kitchen converge default-ubuntu-1404` now fails differently, and earlier:

```
% kitchen converge default-ubuntu-1404
-----> Starting Kitchen (v1.3.1)
-----> Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Berksfile, Cheffile, cookbooks/, or metadata.rb not found so Chef will run with effectively no cookbooks. Is this intended?
       Removing non-cookbook files before transfer
       Preparing solo.rb
       [SSH] connection failed, retrying (#<Errno::ECONNREFUSED: Connection refused - connect(2) for "192.168.59.103" port 49168>)
       [SSH] connection failed, retrying (#<Errno::ECONNREFUSED: Connection refused - connect(2) for "192.168.59.103" port 49168>)
$$$$$$ [SSH] connection failed, terminating (#<Errno::ECONNREFUSED: Connection refused - connect(2) for "192.168.59.103" port 49168>)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [Connection refused - connect(2) for "192.168.59.103" port 49168]
```

**Comment by peterabbott** [comment]
It is because you are overriding the run command so the sshd deamon is not running. 

The driver sets its own run_command:
https://github.com/portertech/kitchen-docker/blob/master/lib/kitchen/driver/docker.rb#L36

You should not really rely on /sbin/init when using Docker containers. If you really do need to start services then consider supervise, but from experience I'd not go down that route.

**Comment by jordansissel** [comment]
> You should not really rely on /sbin/init when using Docker containers

Predictably, I expected this response. My particular endeavor requires a real init system to test against. If you need context, see https://github.com/jordansissel/pleaserun.

Any recommendations on having kitchen-docker running init and also starting sshd? Custom Dockerfile per machine? Any prior art in this area?

**Comment by peterabbott** [comment]
One of the key ideas around using Docker is to run single process in their own container and then linking them together (if required). From memory, Docker actually replaces /sbin/init with their own version.

Even when running init, Docker does things behind the scene that means services are not started automatically, you need to each one manually. I went through the pain of discovering that 6 months ago. 

One option is to use supervisor which is the recommend approach from the Docker team if you do actually need more than one service running.   

The other option would perhaps try the driver https://github.com/marcy-terui/kitchen-docker_cli as it uses docker exec to copy stuff across instead of ssh/scp. Still not sure it will work though, as you would still have to start the services manually.

Looking at the project you have, maybe you have to add support for supervise when running in a Docker container? Or a helper that works out what services to start?

**Comment by jordansissel** [comment]
@peterabbott you are really not understanding what I am asking. "Use supervisord" is a solution to a problem I do not have. I am not asking for a lesson on what you believe Docker to be for.

This kind of "Let me tell you how I use Docker, and therefore your way is wrong" is the same noise I get nearly every time I ask questions near the Docker community.

I'm out.

**Comment by peterabbott** [comment]
Then I guess Docker is the wrong tool for the problem you are trying to solve. 

If the Docker team are suggest you to use supervisord then using anything else is probably just going to be waisting your time.

I was in the same spot you were a few months ago, trying to get upstart working. I just didn't work in the way we would expect in other setups. 

Was just trying to save you the pain of discovering what I went through trying to get init.d/upstart running automatically on Docker.

**Comment by aerickson** [comment]
I'm in a situation similar to @jordansissel.

I'm using kitchen-docker because kitchen-vagrant (virtualbox) doesn't work on cloud CI systems, not because I want to use docker. I need to test a setup that uses SysV init. All of my ansible is failing because SSHD isn't running. 

It would be nice if there was a way to make this work.

**Comment by coderanger** [comment]
@aerickson Unfortunately this is a good example of how Docker is _not_ the same as a tiny VM. It's close, but definitely not the same thing. SysV is functionally dead at this point so most effort is going to making systemd work well for testing, and even that is currently way harder than it should be with kitchen-docker. I would recommend using something like kitchen-ec2 or another cloud driver if you really do need true VMs.

**Comment by aerickson** [comment]
Thanks. Realized my setup used Upstart and found this.

http://www.tddfellow.com/blog/2015/08/05/running-kitchen-docker-tests-with-upstart/

**Comment by 3rawkz** [comment]
People are so touchy jesus...delicate sensibility I mean ...*SIGH* Yes supervisord would fix the issue then again , fix the root of the issue, moe than like ly as aerickson said, sound like theres an upstart assigned to it yeh? Yeah.... can be considered a virtual enviroment since procces do come in and out fro the container to the pc ... making its have the awesome flexibility but also being a HUGE security issue being that the distrobustion of images really sisnt just get started being scanned and sanitized on cokers repos and and I dound gitbud does any that....  Almost makes me think every docker image should have snort or w.e IDS just attached.... HA! and possibly a supervisord to ... keep it tight.
