### ISSUE TITLE
Fedora - Running docker with sudo prevents kitchen from working (list and create).

### ISSUE THREAD

**Issue by sladiri** [portertech/kitchen-docker#158]
I cannot run kitchen list and kitchen create:
I haven't setup my user to be in the docker group, but I added an entry in the sudoers file instead. I can run 'sudo docker ps -a' successfully for example.
I have an alias 'docker=sudo docker' also.

I see two problems:
1.
In this situation 'kitchen create' fails with the error described here: https://github.com/portertech/kitchen-docker/issues/54#issuecomment-52043318
It looks like the command isn't executed with sudo, then the sock file is denied.
I can't see how the comment about this helps: https://github.com/portertech/kitchen-docker/issues/54#issuecomment-52046236

2.
'kitchen list' uses 'sudo -E' which doesn't work in my situation, as explained here: https://github.com/portertech/kitchen-docker/issues/54#issuecomment-52012749
If I add  'use_sudo: false' to .kitchen.yml and create an alias 'docker=sudo docker' I can run 'kitchen list', but the first problem remains.

kitchen.yml:
    ---
    driver:
      name: docker
      use_sudo: false

    provisioner:
      name: chef_zero

    platforms:
      - name: centos-7.0

    suites:
      - name: default
        run_list:
          - recipe[kitchen_init::default]
        attributes:

It would be nice if kitchen-docker supported running docker as sudo.

Regards

**Comment by coderanger** [comment]
Aliases are shell constructs, they have no effect on other programs. You could make a wrapper script instead of an alias though. Alternatively you could use docker over a TCP socket on localhost, though without authentication this would have significant security ramifications. In any case, you need to be able to run docker somehow, either directly, via `sudo -E` (because in the general case we want to preserve `$DOCKER_HOST` and similar variables), or via a socket.
