### ISSUE TITLE
"Authentication failed for user kitchen@localhost" when converging in parallel (since 2.2.0)

### ISSUE THREAD

**Issue by tknerr** [portertech/kitchen-docker#160]
After updating from kitchen-docker 2.1.0 to either 2.2.0 or 2.3.0 I'm getting `Authentication failed for user kitchen@localhost` errors when converging two instances in parallel.

Source code for reproducing the issue on this branch:
https://github.com/tknerr/sample-toplevel-cookbook/tree/gem-updates/

Here are the relevant builds on CircleCI:
https://circleci.com/gh/tknerr/sample-toplevel-cookbook/tree/gem-updates

You can see:

* build 314 was still OK
* build 315 failed after updating to kitchen-docker 2.3.0 (along with some other gem updates)
* build 316 was just a rebuild of 315 to see if it's reproducible -- and it failed too
* build 317 was passing again after I switched kitchen-docker back to 2.1.0 (see https://github.com/tknerr/sample-toplevel-cookbook/commit/f708e83cd42943e4497c3bf9f5805edec3d6aa26)
* build 318 failed again after switching kitchen-docker to 2.2.0

Reading the CHANGELOG I suspect it might be the "Passwordless suite instance Docker container login (SSH), using a generated key pair." feature introduced in 2.2.0 that makes it break.

Is there anything I would need to adjust in my .kitchen.yml to make this work? Or is it indeed a bug when converging in parallel?

**Comment by looztra** [comment]
we also hit the same issue. we are using the same workaround.

I may spend some time to try to figure out what is going wrong

**Comment by coderanger** [comment]
Hmm, so the SSH key pair should only be generated once the first time. This process has a race condition, so I could see it failing on the first parallel attempt, but after that it should be fine because the files will exist under `.kitchen` so no race condition. This would be a problem in CI though, where it gets a blank file system on each run. The fix will be to mutex around https://github.com/portertech/kitchen-docker/blob/master/lib/kitchen/driver/docker.rb#L140-L142 a bit more.
